default_environment: &default_environment
    docker:
      - image: efficienthealth/node-awscli:latest
    working_directory: ~/ratio-amz-rekognition

version: 2
jobs:
  test:
    <<: *default_environment
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: npm-install
          command: 'npm install'
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
          - ./node_modules
      - run: npm run test:ci

  # This step generates an unique service version to be passed, as environment variable, to serverless.
  # The generated version uses the major and minor version numbers from the package.json file and appends
  # a timestamp and the build number:
  # i.e: 1.0.171010.21
  generate_service_version:
    <<: *default_environment
    steps:
      - checkout
      - run: mkdir -p workspace
      - run: echo `python ./tools/generate-service-version.py $CIRCLE_BUILD_NUM` > workspace/SERVICE_VERSION
      - persist_to_workspace:
          root: workspace
          paths:
            - SERVICE_VERSION
  
  deploy_dev:
    <<: *default_environment
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - attach_workspace:
          at: workspace
      - run: echo `cat workspace/SERVICE_VERSION`
      - run: echo 'export SERVICE_VERSION=`cat workspace/SERVICE_VERSION`' >> $BASH_ENV
      - run: echo $SERVICE_VERSION
      - run: export STAGE=dev && 
             export REGION=$dev_AWS_REGION && 
             npm run deploy

  deploy_qa:
    <<: *default_environment
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: export STAGE=qa && 
             export REGION=$qa_AWS_REGION && 
             npm run deploy

  deploy_uat:
    <<: *default_environment
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: export STAGE=uat && 
             export REGION=$uat_AWS_REGION && 
             npm run deploy

  deploy_prod:
    <<: *default_environment
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: >
             export STAGE=prod && 
             export REGION=$prod_AWS_REGION && 
             npm run deploy

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - generate_service_version:
          requires:
            - test
      - deploy_dev:
          requires:
            - generate_service_version
          filters:
            branches:
              only:
                - dev
      - deploy_qa:
          requires:
            - generate_service_version
          filters:
            branches:
              only:
                - qa
      - deploy_uat:
          requires:
            - generate_service_version
          filters:
            branches:
              only:
                - uat
      # - deploy_prod:
      #     requires:
      #       - test
      #     filters:
      #       branches:
      #         only:
      #           - master
